id = "lean4"
name = "Lean4"
version = "0.0.1"
schema_version = 1
authors = ["Narazaki Shuji <shnarazk@protonmail.com>"]
description = "Lean4 extension"
repository = "https://github.com/shnarazk/zed-lean4"

[grammars.lean4]
repository = "https://github.com/shnarazk/tree-sitter-lean4"
commit = "aa5bffe260b08cad6b2d8086e1684a5c3732d062"

[language_servers.lean]
name = "lean"
language = "Lean4"
