id = "lean"
name = "Lean"
version = "0.0.1"
schema_version = 1
authors = ["Narazaki Shuji <shnarazk@protonmail.com>"]
description = "Lean4 extension"
repository = "https://github.com/shnarazk/zed-lean4"

[grammars.lean]
repository = "https://github.com/shnarazk/tree-sitter-lean"
commit = "f66b84f5ea1d0545aaa8b2a42153e4beeb33c90c"

[language_servers.lean]
name = "lean"
language = "Lean"
