id = "lean4"
name = "Lean4"
version = "0.0.1"
schema_version = 1
authors = ["Narazaki Shuji <shnarazk@protonmail.com>"]
description = "Lean4 extension"
repository = "https://github.com/shnarazk/zed-lean4"

[grammars.lean]
repository = "https://github.com/Julian/tree-sitter-lean"
commit = "1d230008e22b9f506cf4a4012e2b46debfe30243"

[language_servers.lean]
name = "lean"
language = "Lean4"
